# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM_Assignment' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM_Assignment

	pod 'Alamofire'
	pod 'SwiftyJSON'

  target 'MVVM_AssignmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
